### ISSUE TITLE
Allow `ConsoleModuleLoader` to load multiple modules

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#100]
The `ConsoleModuleLoader` makes use of the global `moduleDirectory` variable, which is referenced by the non-member function `GetArtPath`. This design has several limitations. One being that it complicates testing. Another being this restriction is at the core of why the `ConsoleModuleLoader` only supports a single loaded module.

The `GetArtPath` method is current used to overwrite the two calls from within Outpost2.exe to `CConfig.GetString("DEBUG", "ART_PATH", ...)`. It is effectively hiding the ini file settings:
```
[DEBUG]
ART_PATH = ...
```

Years ago, it was discovered this setting could be used to load resources from the `ART_PATH` setting, outside of the root game folder. The above functionality was added to the console module loader as a way to load mod specific resources in a temporary way, by overriding the ini setting with a module specific folder set on the command line. This is however a bit of a hack, as it's limited to loading resources from a single extra folder. It also prevents the ini file `ART_PATH` system from working, though that setting had been unused before.

----

As we now know more about the resource finding/loading algorithms, perhaps we can design an alternative patch that could allow inserting multiple resource search paths into the game. That would lift the restriction on loading only a single console module, and perhaps allow for easier test code.

One likely place to hook is:
```
00471590  Function: ResManager.GetFilePath(char* resName, [out] char* filePath):bool bSuccess
```
The above method is one of the places where `ART_PATH` is checked. It appears to check the `ART_PATH` location first, then the game folder, then the CD. If we hooked this method, we could insert a search of prioritized module folders before those other locations.

The `GetFilePath` method is called by `ResManager::OpenStream`. If the `GetFilePath` method succeeds, the stream is opened as a file from disk, otherwise it falls back to searching the VOL files. The `ResManager::OpenStream` could be another potential place to hook, however it's called from fewer places, so could not be used to hook as many potential resources. In particular, methods that process level DLLs call `GetFilePath` directly (thought: custom campaigns). As such, the `GetFilePath` method is likely the preferred place to hook.

----

Side note: The other use of `ART_PATH` doesn't seem to be used. There are no known calls or references to the other method, and playing the game does not trigger a breakpoint set on the other method:
```
00471B60  Function: ?(const char* fileName?):bool bSuccess
```
It may be the use of `ART_PATH` in this method is never used, and was hooked simply because it was the only other reference to it.

----

The other side of this problem would be updating the command line argument processing to support loading of multiple modules.

**Comment by DanRStevens** [comment]
Correction to the above:

The second method that accesses `ART_PATH` is for creating write streams. It is an exported method. The corrected signature is:
```
00471B60  Function: ResManager.CreateStream(const char* fileName):StreamIO* fileStream
```

A local user label in OllyDbg stopped it from presenting the export info, hence why I'd previously marked it as an unknown function. OllyDbg couldn't find any references to it within the Outpost2.exe module, and running the game didn't catch any breakpoints for it. It may actually be unused.

I tried checking if saving games would cause writes through the `CreateStream` method, but it doesn't. It seems the saved game code creates the write streams directly, without using this method.

I'm uncertain what if any use the `ART_PATH` setting would have on stream write locations.

----

I had initially hoped the `ART_PATH` setting could be used to redirect saved game writes for a custom campaign module. It would be sensible to only have campaign saved games available when a campaign module is loaded, as they may not make sense to the game engine otherwise. The Renegades expansion written by Eddy-B had it's own saved games separate from the original set. He did that with his own custom code hooks though.

----

In terms of updates, I'm not certain we want to redirect the write location of `CreateStream` when a module is loaded. It's not clear what this would be used for, or if it's even useful at all. Perhaps we should leave such redirects to modules themselves, as they would have a better sense if it was needed.

I think hooking `ResManager.GetFilePath` is sufficient to support loading multiple console modules.

**Comment by DanRStevens** [comment]
PR #110 has now been merged in. That should unblock this issue.

PR #120 may touch some of the same code, so we might want to finish that work first to avoid merge conflicts.

----

This work hinges on the global `moduleDirectory` variable. Previously `moduleDirectory` was used in the `GetArtPath` method, and it was used in such a way that it could only return a single value. Now that usage has been removed, and there is a corresponding use in the replacement `ResManager::GetFilePath`. In this new method, we are free to loop over an array of paths, and choose the first one that contains a given file. Assuming none of the folders contains a file of the given name, we can then fall back to the original method from Outpost2.exe, which checks the VOL files.

I propose we replace this `std::string` variable with a `std::vector<std::string>`, and implement a loop within `GetFilePath`. Further, we need to update the constructor of `ConsoleModuleLoader` to add the console module's path to the list, rather than simply set it. We would also need to update the global variable definition in `op2ext-Internal.cpp`. That is the only reference to the global outside of `ConsoleModuleLoader.cpp`, and is only needed to ensure a well defined static initialization order between that and the current global `ConsoleModuleLoader` instance.

----

We would also need to update the argument parsing so multiple console modules can be parsed from the command line and loaded. We should decide if we want multiple `loadmod` options to be passed, or if we want a single `loadmod` option to handle a list of module names.

At some point we need to decide if `ConsoleModuleLoader` will load all modules with a single instance, or if we instantiate it multiple times, once for each module loaded. I suspect we'll want to use just a single instance, as we'll need the `vector` of loaded modules/paths, which would fit logically in a class that loaded them all (even if it's as a static member).

The `moduleDirectory` variable, or rather it's future `vector` equivalent could be moved into the `ConsoleModuleLoader` class as a private static (with `friend` access given to the replacement `ResManager::GetFilePath`). This may require some updates to the static initialization order requirements.

We'll want to better address the static initialization order issue. We have two global variables with non-trivial construction, `consoleModLoader` and `moduleDirectory`, where one depends on the other. This means they need to be defined in the same file to ensure a consistent static initialization order. By breaking the dependency, we can free up where those global variables may be defined. We could also look into making them non-global, though I think it would still be good if we allowed a global `ConsoleModuleLoader` instance without any specific requirement on where the `moduleDirectory` or future `vector` version of it was defined.

To address the static initialization order requirement, we may want to rework how data flows through the `ConsoleArgumentParser.cpp` file, and in particular the `FindModuleDirectory()` method. That method will have to be updated anyway, as there will be multiple console modules, and so it will need a parameter added to identify the module, or would need to be updated to return an array of directories for every module.

Finally, some of the module count code has a built in assumption that there is only a single console module loaded.

**Comment by DanRStevens** [comment]
The DLL API `GetConsoleModDir_s` function may need to eventually be deprecated. Its parameters have a build in assumption of a single console module. There is no way to specify a module index:
```
OP2EXT_API size_t GetConsoleModDir_s(char* buffer, size_t bufferSize);
```

A reasonable model to follow might be the related module name method:
```
OP2EXT_API size_t GetLoadedModuleName(size_t moduleIndex, char* buffer, size_t bufferSize);
```

To be consistent, the `moduleIndex` should probably be a global module index, not something tied specifically to console modules. For now, we could potentially return `""` for modules that aren't console modules.

----

If we are to be generic about module folders, we will need to define what they are in the context of other modules. In particular INI modules, though also the built in modules. We should probably do this, as it could allow more modules to be loadable as either an INI module or as a Console module.

To support a more generic concept of module folders, we should add a new `virtual` method to the `GameModule` class. For console modules it can simply return the module name. For other derived classes, they may need a new field to hold the module directory.

I'm thinking modules that don't require additional resource loading can have a module directory of `""` to indicate this. We might even add a default virtual method implementation that returns `""`.

----

We should review the index order of modules. Currently they are commented to index the INI modules first, followed by console modules. We should probably update this, particularly in regards to build in modules. We should probably index things based on the order the modules were loaded. As console modules are loaded before ini modules, they should probably be indexed first.

Within a given type of module (console, or ini), I believe they are already indexed in load order.

----

The old console module code checks against a module name of `""`, and special cases that to mean no module loaded. The new array concept is more like an empty array `{}`.

We should give some though to what it means if `""` values are found within the array. In particular, they may be found multiple times.

Additionally, multiple console modules means we can potentially have duplicate names within the console module list. This will need to be handled.

We also need to think about how duplicate names are handled between the different module sources. It might be that a console module name has the same name as a built in module, or an INI module.

As a bit of a side note, I think it should be possible to turn off a built in module, and then load a console module or INI module with the same name. That would allow for replacements or upgrades to built in modules. In particular, it could be a way to test large updates, particularly if a built in module grows to a point where it is split out into an external module.

**Comment by Brett208** [comment]
This issue is starting to creep into a large scope... Maybe best to make other issues to handle some of the larger concerns outside of just allowing multiple console modules (although some of this is all tied together in a knot with the issues brought up).

Each module only should need to concern itself with its own directory. I know we can detect the name of the dll that is calling our API. Right now it just applies for error logging. What if we extended this concept for the function GetConsoleModDir_s? If we knew which module called to get its directory, we wouldn't need to break the API or burden the external module with figuring out which index it is. 

My first thought was to just use the logging code, but all console modules must have the same filename, so I don't think that will work. Maybe there is a way to capture the hInstance of the module on call of the function and compare with the stored hInstance in the Ini/ConsoleModule. Or maybe there is a way to record what base address the dll is loaded at and again retrieve it when GetConsoleModDir_s is called? I've done no research on the concept, just some thoughts. 

Currently IniModules and BuiltInModules will be rejected if they have the same name. I was planning to extend this to ConsoleModules when unifying ConsoleModules with the ModuleLoader. Of course if a BuiltInModule is not loaded, it would allow an ExternalModule to take the name. 

My opinion is that order of precedence should be BuiltInModules, ConsoleModules, then IniModules. So I would like to eventually switch the source code so ConsoleModules load before IniModules. I suspect this reordering occured because of the ModuleLoader now handling BuiltInModules which should be loaded first (I think, not that I am dead set on this order, just off the top of my head).

Hope this helps.

-Brett

**Comment by DanRStevens** [comment]
... yes, you seem to be right about the scope creep. I had originally envisaged this as a fairly small and quick change to make. It has already resulted in multiple independent code changes, with plenty more to come. A step-wise approach will definitely help here.

You make a very good point about `GetConsoleModDir_s` being mostly used by the console module itself. The idea of detecting the module using the `hInstance` is actually an excellent solution. We could use the same `ReturnAddress` trick from the logging code. The return address could be compared to module address ranges to map it back to a module handle, which we could track when we load the modules.

Of course we would need to handle the case when the method is called from outside of a console module. It could be called from an ini module, or something else that doesn't correspond with a game module. In that case, maybe return the first loaded console module details, or nothing as if no console module was loaded. Returning nothing would be a change in the existing semantics though.

I agree with the ordering of BuiltInModules, ConsoleModules, then IniModules.

Currently console modules are loaded before ini modules. They're also loaded before built in modules right now, which should probably change. I'm sure that will be fairly natural to fix once we unify the module loading a bit more.

**Comment by DanRStevens** [comment]
This issue was originally concerned with replacing the `ART_PATH` hook with a more flexible `ResManager::GetFilePath` hook. That has now been accomplished. The remaining points in this issue should perhaps be moved to new issues, and this one closed.

The most important outstanding issue (according to the topic title) is:
- Update command line argument processing so multiple modules can be loaded at the command line.

Side points:
- Unify the differences between INI modules and Console modules, in particular generalizing the concept of a module folder. See Issues #117 and #147.
- Update index ordering of loaded modules. Honestly I think we can just remove the specification of the order. Information can be found in some order, but we don't care much what order. If we happen to return modules in load order, so be it.
- Have `GetConsoleModDir_s` adapt to return module folder of calling module. If called from a non-module, perhaps return `""`, or the directory of the first loaded console module, if any.
- Add checks for duplicate modules names. This might be done in the command line argument processing, and most certainly in the `ModuleLoader`.
