### ISSUE TITLE
Add tests for decent log messages

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#107]
I was looking at PR #103, and thought I'd add a few ideas here post merge.

You can potentially use [String Matchers](https://github.com/google/googletest/blob/master/googlemock/docs/CheatSheet.md#string-matchers) from the Google Mock library to scan for output strings. It may be wise to delete and recreate the log file between tests if you're scanning for test output. That can be done in the `SetUp` and `TearDown` methods of a test fixture.

It may also be wise to move the global `logPath` variable into the `SetUp` method. That way any problems with initialization will be tied to a particular test, rather than possibly making the whole test executable fail before it even starts to run tests. (I've wondered if such a reason involving different code is why the current Linux CI tests often crash).

This could become part of `SetUp`:
```cpp
const fs::path logPath = fs::path(GetGameDirectory()).append("Outpost2Log.txt");
```
We might also want to put in a utility method for reading the log file into a string for use with test matchers.

**Comment by Brett208** [comment]
I would support a more robust log testing. PR #106 includes code to check if the ConsoleArgumentParser outputs to log files. This is done the same as the current logger tests, by checking if log file sized increased.

Making this test more sophisticated by checking for specific strings or date time stamp ranges, etc would be a good idea. Not sure I personally plan to pursue at this time when stacking with other priorities.

-Brett

**Comment by DanRStevens** [comment]
Tagging #131 as related.

**Comment by DanRStevens** [comment]
The logging code was recently been significantly updated. The work done in PR #141, to resolve the design considerations from Issue #131, has been completed. Included is a `MockLogger` class. This can be used to capture error messages from deep inside other method calls. The `CALL` expectations can be combined with string matchers to test the contents of error messages in very flexible ways.

I checked the Google Mock documentation for examples of how to do this. The [gMock Cookbook](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md) has a section titled [Using Matchers](https://github.com/google/googletest/blob/master/googlemock/docs/cook_book.md#using-matchers) with some sample code. One reformatted example with a string matcher for a mocked object named `foo` that has a mocked method named `DoThat` with 2 parameters, one of which accepts a string to be matched:
```
// The first argument must not contain sub-string "blah".
EXPECT_CALL(
  foo,  // Mock object
  DoThat(  // Mocked method that will be called
    Not(  // Matcher for first argument
      HasSubstr("blah")
    ),
    NULL  // Matcher for second argument (exact value match with NULL)
  )
);
```

----

Applying that to an example for our code base, we might have something that looks like:
```
TEST(SomeMethod, SomeMethodHasDecentErrorMessage) {
	MockLogger logger;
	// When method under test eventually runs, it should result in a call that matches this
	EXPECT_CALL(logger, Log(HasSubstr("file not found"), "op2ext.dll"));

	// Install test logger
	EXPECT_NO_THROW(SetLogger(&logger));

	// Test the code that triggers an error to be logged
	// Logged message will be checked against pre-set expectation
	SomeMethod();

	// Remove test logger
	EXPECT_NO_THROW(SetLogger(nullptr));
}
```

This can be further extended to use a test fixture to create the `MockLogger`, install it, and remove it at the end of the test. The test body would then contain only the `EXPECT_CALL` setup, and the call that triggers the log message `SomeMethod()`.

**Comment by DanRStevens** [comment]
This issue largely dealt with support code to accomplish log message testing. That was completed in PR #165. Since then the support code has been used in a few different tests.

As there are no specific areas of the code marked as needing log message testing, I think we should close this as finished.
