### ISSUE TITLE
Remove dependence on Outpost2DLL

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#113]
Currently op2ext relies on Outpost2DLL to link to two `TApp` methods. This dependence prevents buildings and testing op2ext.dll on Linux due to name mangling differences with the Mingw compiler.

In Issue #100 and PR #102 / PR #110, an alternate linking method was developed to hook the resource search path. (Currently this method needs debugging due to a crash problem). This same method could be applied to the `TApp` linking. That would solve the above Linux compilation issue.

Although the proposed linking code seems to contain a bug, applying the same method to the `TApp` linking code could allow for compiling and debugging of the proposed code on Linux.

Related to the above, the makefile could be updated to support building the DLL or the static lib as separate projects.

**Comment by DanRStevens** [comment]
PR #116 cleaned up the Makefile and added rules to build either the DLL or the static library as separate targets. This removes one of the impediments to working on this issue.

**Comment by Brett208** [comment]
Can you actively run Outpost 2 with op2ext compiled on Linux now?

Thanks,
Brett

**Comment by DanRStevens** [comment]
Yes. Though it does crash upon exiting due to the Mingw code generation problem when it tries to call the original `TApp.ShutDown()`. Annoying, but good enough to run some quick and dirty manual tests. Maybe not yet quite so good for automated tests.
