### ISSUE TITLE
Unify ModuleLoader

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#117]
I would like to consider unifying the 2 existing game module types and adding a third module type using inheritance. A base abstract class called GameModule and an inheritance tree of modules that are all handled by the same ModuleManager after being loaded.

```C++
#include <string>

// Abstract class allowing memory modification of Outpost 2 to alter gameplay or fix bugs
class GameModule
{
public:
    GameModule(const std::string name) : name(name);
    virtual ~GameModule() 
    inline std::string Name() { return name; } const;

    virtual void Initialize(); //mod_init(), InitMod
    // Only available for Console modules (other modules would just call an empty function)
    virtual void Run() = 0; //mod_run()
    virtual void Destroy() = 0; //mod_destroy(), DestroyMod

private:
    const std::string name;
}
```

```C++
#include <windows.h>
#include <string>

// Game Module identified by command line switch. Use for modules that should only occasionally be loaded from the command line.
class ConsoleModule : GameModule
{
public:
    ConsoleModule(const std::string& name, const std::string& moduleDirectory) : GameModule(name), moduleDirectory(moduleDirectory);

    std::string GetModuleDirectory() const;

    void Load() override;
    void Initialize() override;
    void Destroy() override;

private:
    const std::string moduleDirectory;
    HINSTANCE dllHandle;
}
```

```C++
// Game module identified in INI file with logic contained in a separate dll. Use for large modules  designed for semi-permanent use.
class IniModule : GameModule
{
}

// Internal modules. Use for small patches where creating a full new project and dll are not practical.

class IPDropDown : GameModule
{
}

class GarageSaveCrash : GameModule
{
}

class BuildingGroupHang : GameModule
{
}

// and so on...
```

For cleanup, ini modules and console modules use the function Destroy. I would prefer the word Unload over Destroy, but maybe best to stick with Destroy since the EXPORT functions use it.

My biggest concern is dealing with memory modification of functions from within the classes. When attempting to patch Outpost2 from a class called GarageSaveCrash, if the function is defined within the class, it will include the hidden argument detailing which class the function is a part of. I don't know if we can easily overcome this.

Once solution could be to define replacement functions in the class's cpp file but outside of the class. This seems maybe a bit contrived/awkward though.

If this has merit, it would need more fleshing out. I'd be willing to do a lot of leg work although someone else would have to help me with the memory hooks.

Thanks,
Brett

**Comment by Brett208** [comment]
@DanRStevens 

I'm going to start writing code for this issue, so please let me know soonest if you have objections and would prefer I wait.

Thanks,
Brett

**Comment by DanRStevens** [comment]
We should have @Arklon1 take a look at this.

----

I like the plan you've presented. This seems like a good idea.

I'd be fine with renaming `Destroy` to something like `Unload`. That does sound like a better description.

For control of hidden `this` pointers, you can declare a method as `static` to get rid of it. If you want the hidden `this` pointer to represent a different class, you can define another possibly nested class to contain the method.

----

For `GameModule(const std::string name) : name(this->name);`, I think you want to get rid of the `this->` part, as that would cause the uninitialized `name` field to be initialized with itself, which is still uninitialized.

**Comment by Brett208** [comment]
Okay, I'll plan to use Unload.

Maybe we should try making the functions static first and if that doesn't work just deal with some of the code in the .cpp file being outside the class.

Thanks for noticing the this-> error.

I am thinking all the mods should be placed in a GameModules folder.

Happy to hear if Arklon has ideas/criticism/etc.

Starting Sequence:
1. Define GameModule abstract class
2. Rewrite IPDropDown to be a child of GameModule
3. Write a ModuleManager class and have IpDropDownModule register with it
4. Write IniModule class

If there is a better name than ModuleManager, happy to use it.

Thanks,
Brett

**Comment by DanRStevens** [comment]
Hmm, maybe "ModuleLoader"?

Actually, I was thinking earlier today we should update the description of op2ext. It says "Outpost 2 extension module", but perhaps it should say "Outpost 2 extension module loader". Sure, it is an extension module itself of sorts, but its main purpose is to load other extension modules.

**Comment by DanRStevens** [comment]
I'm curious, do you consider this issue done now? Or is there still more you want to do? It seems like the objectives listed above have been met.

**Comment by Brett208** [comment]
To close this issue out, we need to:

1. Create a ConsoleModule class that inherits from GameModule
2. Have ConsoleModuleLoader create the a ConsoleModule and pass it to the ModuleLoader

There are some implementation details that I'm probably glossing over.

I'm not actively coding much right now if you are looking to take this on, just take ownership of this issue. I may have time later this week...

**Comment by Brett208** [comment]
I am fairly close to being ready to post this code. It involves a large changeset.

-Brett
