### ISSUE TITLE
AppVeyor Organization Account

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#12]
I came across some info about setting up an [AppyVeyor Organizational Account](https://www.appveyor.com/docs/team-setup/). Currently all our AppVeyor builds are run on personal accounts, where only one person has access to organizational settings. This is fine for getting started, though limits who can adjust build configuration settings.

I propose creating an organizational account, and then moving current AppVeyor builds to the organizational account.

One blocking issue is an organizational account needs it's own email address. I asked BlackBox to setup an organizational email using the "@outpost2.net" domain. It may be setup as a subscribe type email list. Once that is done, we can use it to create an AppVeyor organizational account.

**Comment by Brett208** [comment]
Completely onboard with transferring ownership once a reasonable solution is determined. 

-Brett
