### ISSUE TITLE
Console Module Resource Loading Broken

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#121]
As discovered in #110. It seems the ConsoleModLoader used to be able to load VOL files from the module directory, which would override built in VOL files. Currently this is broken.

The ConsoleModLoader should still be able to load loose files from the module folder, which will override the built in defaults. That part continues to work.

A possible solution might be to add `LocateVolFiles(consoleModLoader.GetModuleName())` in `ExtInit` in DllMain.cpp before it adds other VOL files, such as in the "Addon" folder. That should restore loading of VOL files form the console module folder, and have them take priority over the built in ones.

I believe this broke back when custom VOL lists were implemented. Previously VOL files were loaded by the game in `ResManager.Init()`, using `ResManager.GetFilePath`. The op2ext library changed this to search for VOL files itself, and load them directly, bypassing the internal mechanism, and the ability to override it with the `ART_PATH` setting or by later hooking of `ResManager.GetFilePath`.

**Comment by Brett208** [comment]
This should be a priority fix before the next formal release. It may be broken in the last release of op2ext.

**Comment by DanRStevens** [comment]
It looks like the bug presented here has been resolved satisfactorily.

Before closing this, should we add corresponding code for INI loaded modules? That would make module use much more symmetric. Then a module could be loaded either through the console, or through the INI file, and it would load resources along with it. We could also push this to a new issue. Loading of non-packed files would also need to be looked at.

**Comment by Brett208** [comment]
I would prefer opening a new issue although I support the idea of ini files loading resources from their local directory.

**Comment by DanRStevens** [comment]
Ok, new issue opened for tracking the corresponding update for INI modules. Thank you for the feedback.
