### ISSUE TITLE
VS placement of `AdditionalDependencies`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#125]
The op2ext project makes use of some Winsock functions in the `IpDropdown` code. These need a library reference set under `AdditionalDependencies`. I believe Visual Studio will let you set this under either the DLL project or the static library project, and it will work. If set in neither, I believe it will error out when linking the DLL project, giving an error about undefined symbols. I don't believe it will ever error out when building the static library project if no reference is set. Static libraries don't need their own imports to build.

In PR #124 I solved the problem by having the DLL project include the Winsock library. In PR #120, it seems it was solved by putting the reference in the static library project, and removing the reference from the DLL project.

My guess is, the reference needs to be set in at least one of the two projects. If set in the static library project, I suspect Visual Studio will transitively include it when linking the DLL project. We should verify if this is true. If so, we may want to move the reference back to the static library project, as anything using it may need to have that reference set.

Curiously the unit test project does not have a reference to the Winsock library, and it hasn't complained. I suspect this is because the unit tests don't actually make calls into the IpDropdown code, and so the Winsock methods never end up being referenced by the unit test executable. If we added some IpDropdown related tests to the unit test project, I suspect it might start failing to link. If so, the solution would be to add a reference to the Winsock library to the test project, or perhaps better, we move the Winsock library reference back to the static library project, and remove it from other projects.

**Comment by Brett208** [comment]
I would prefer winsock be included in the static library unless we have a specific reason to push it to the DLL project. I think this improves tracing dependencies by placing the linker requirement closer to the source. 

Also, I put the winsock dependency on the static project in PR#120 because I used IPDropDown in some of the unit tests for the ModuleLoader, which was failing to compiling on MSVC without the winsock reference. It wouldn't be inappropriate to switch the use of IPDropDown to some sort of test GameModule, although I generally still want winsock.h referenced by the static project.

Sorry, I didn't read your changes in PR#124 close enough or would have complained before approving. 

Thanks,
Brett

**Comment by DanRStevens** [comment]
I agree. Assuming Visual Studio propagates the additional library includes to projects that depend on the static library, it would be best put in the static library project file.

I'm glad you made some mention about it in the other thread. I probably wouldn't have missed it completely if you hadn't said something to raise my curiosity.

**Comment by DanRStevens** [comment]
I noticed something a bit odd. There are currently references to `wsock32.lib` from both the DLL project and the static library project. They are under different sections though.

The DLL project had the settings, among others, under `<Link>` section:
```
<Link>
  ...
  <AdditionalDependencies>wsock32.lib;%(AdditionalDependencies)</AdditionalDependencies>
  ...
</Link>
```

The static library project also had that setting, but without the library listed. Instead, the library was listed alone under `<Lib>` section:
```
<Lib>
  <AdditionalDependencies>wsock32.lib</AdditionalDependencies>
</Lib>
```

I'm not sure what the difference is between these two sections, or where the settings should go. Ideally there is one single place to put the setting so that all projects in the solution will build.

@Brett208, as this is a Visual Studio project configuration issue, perhaps you would be better able to experiment with this.
