### ISSUE TITLE
Update documentation before next release

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#138]
We need to update documentation before new release to include: 

* new names BuiltInModules and ExternalModules
* The fact that ExternalModules have 2 subtypes, ConsoleModules and IniModules
* How BuiltInModules are loaded
* New behaviour of Console Modules that do not replace volumes, but load same named volumes before the game does

Places to look at updating:
* Readme
* SampleModules folder
* op2ext.h (public include)
* TestModule comments

**Comment by Brett208** [comment]
- [ ] Update dll resource to be version 3.0
- [ ] Update readme to include multiple console module loading
- [ ] Update readme to include what a built in module is and how to turn them on/off
- [ ] Update readme on new syntax for loading ini modules
- [ ] Remove any references to deleted public functions IsConsoleModule and IsIniModule
- [ ] Provide documentation on GetConsoleModuleDirectory change in behviour due to multiple console modules
- [ ] Add note in readme that code requires C++17 compliant compiler and that code may be compiled on mingw

**Comment by DanRStevens** [comment]
I would like to tag Issue #214 as related to documentation updates. More generally, any public name that has been recently introduced or modified should be given some consideration.

**Comment by DanRStevens** [comment]
Tagging PR #234 for introducing the (INI) module export name `RunMod`.
