### ISSUE TITLE
Allow loading external modules in the ini file via a full section

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#139]
Currently external modules are loaded like:

[Game]
```
ExternalModules = "NetFix, NetHelper"
```

I wold prefer loading ExternalModules:
```
[ExternalModules]
NetFix = yes
NetHelper = no
```

However, I haven't researched Ini file access enough to know if this is supportable by the winapi. We can get away with this sort of list for BuiltInModules because we know all their names ahead of time. For an external module, we don't know the module's name before compilation.

**Comment by DanRStevens** [comment]
I don't believe the Windows API would have support for using INI files that way. You could certainly do it if you wrote your own INI file parser though.

Of course, that does seem a little against the spirit of how INI files were meant to be used. They were about key/value lookup, for well known configuration settings. But then, I suppose we're already abusing the format with `ExternalModules` by having values that refer to section names.

**Comment by Brett208** [comment]
At this time, I'm not looking to write a custom parser. I guess we can leave this issue on the backburner in case it ever gets realized as I think it would provide better presentation to the user.

**Comment by DanRStevens** [comment]
I agree. It does look nicer, and makes it easier for users to turn modules on/off.

**Comment by DanRStevens** [comment]
I just remembered something from years ago. We can do this without a custom parser. The [`GetPrivateProfileString`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestring) function supports getting all section names, or all key names within a section.

> `lpAppName`
> 
> The name of the section containing the key name. If this parameter is NULL, the GetPrivateProfileString function copies all section names in the file to the supplied buffer.

> `lpKeyName`
> 
> The name of the key whose associated string is to be retrieved. If this parameter is NULL, all key names in the section specified by the lpAppName parameter are copied to the buffer specified by the lpReturnedString parameter.

That was the reason why there buffer size might need to be 2 larger than the string size. Because under certain conditions it can return an array of strings, both the strings and the array may need null termination.

This is similar to how passing `nullptr` in to `WritePrivateProfileString` can be used to clear a key or a section.

**Comment by DanRStevens** [comment]
I was just looking at this. We could write new `IniFile` methods `GetSectionNames` and `GetKeyNames`. Doing so would mean a custom call to `GetPrivateProfileString` with `nullptr` parameters. The current `IniFile::GetValue` method wraps all calls to `GetPrivateProfileString`, but doesn't provide the flexibility to pass `nullptr`. This would need to be refactored, or the functionality largely duplicated for the new use case.

----

I came across this StackOverflow question:
[GetPrivateProfileString - Buffer length](https://stackoverflow.com/questions/10507927/getprivateprofilestring-buffer-length)

It seems there is a maximum buffer length of 2^16 = 65536 characters. Also noted in the long answer, is you can bound a read by the file size. Hence a buffer of `min(65536, fileSize)` is sufficient to hold any value, without looping. The buffer is a bit big, but not so big as to be of much concern. We could potentially resize a `std::string` to hold that much, do the read, and then resize it back down to a reasonable size. That would eliminate the potential need to loop.
