### ISSUE TITLE
Review `UNICODE` handling

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#149]
As noted in PR #135, some of the older existing code is a bit sloppy with regards to `UNICODE` aware functions. In a few places we may have used the generic type, which is able to change string width, in places where a fixed type should be used.

For instance, the `LoadLibrary` call from Outpost2.exe which handles loading the shell DLL has a fixed width. It was baked into Outpost2.exe when it was compiled. Our replacement method uses the generic width names. Changing the `UNICODE` setting in our project shouldn't affect (and doesn't affect) the point in Outpost2.exe which is hooked.

----

On Linux, as quick way to check for errors is to add the following to the makefile:
```
CPPFLAGS := -DUNICODE
```

**Comment by DanRStevens** [comment]
From Raymond Chen's blog:
[TEXT vs. _TEXT vs. _T, and UNICODE vs. _UNICODE](https://devblogs.microsoft.com/oldnewthing/20040212-00/?p=40643)

**Comment by DanRStevens** [comment]
While investigating I encountered one strange problem. The [`MODULEENTRY32`](https://docs.microsoft.com/en-ca/windows/win32/api/tlhelp32/ns-tlhelp32-moduleentry32) struct has a `szModule` field, which is defined as `char`. The related struct [`MODULEENTRY32W`](https://docs.microsoft.com/en-ca/windows/win32/api/tlhelp32/ns-tlhelp32-moduleentry32w) has the same `szModule` field, but is defined as `WCHAR`.

It seems that defining `UNICODE` will map the name `MODULEENTRY32` to `MODULEENTRY32W`. There is no corresponding `MODULEENTRY32A`. I'm not sure if this is a Windows API thing, or a Mingw thing. There's no documentation about it. Similarly, there is no `Module32FirstA` nor any `Module32NextA` function, only the plain or "W" variant.

It would be possible to reference the narrow string version of the struct by using the tag name directly: `tagMODULEENTRY32`. Unfortunately without also using corresponding non-wide versions of the functions, you'll still get type errors. I think I'll leave this one for now.

----

A lot of the issues I looked at were resolved in favour of just using narrow strings everywhere, and the "A" versions of Windows API methods. We could potentially lift some of our narrow string assumptions, though I don't think that's a high priority item.

One possible way to list assumptions is to define a `tstring` object, which could be used in place of `std::string` or `std::wstring`. This is discussed in the blog post [std::tstring](http://www.rioki.org/2010/09/24/tstring.html). I don't quite agree with re-opening the `std` namespace as done in that article though. I think that may be a standards violation. If the standard were to be updated to include an object named `tstring` in the `std` namespace, such code would fail to compile. Instead, it might be better to declare the alias outside of the `std` namespace:
```
using tstring = std::basic_string<TCHAR>;
```

----

Anyway, I recommend we only fix what is easy to do now and just leave the rest. Unicode builds remain unsupported for the time being.

**Comment by Brett208** [comment]
I think grabbing the low hanging fruit here and moving on is a good plan.

For the more library like code inside op2ext I like the idea of it being written in a way that allows use in both Unicode and multi-byte compilation so it can easily be lifted into other projects if needed. I doubt the Unicode handling will ever be needed within Outpost 2 itself though?

-Brett

**Comment by DanRStevens** [comment]
Outpost 2 was compiled to use multi-byte, and there's no real way to change that without the source code. From our end that's mostly only relevant for data structures shared with the game, particularly strings.

It would be nice if the op2ext library code was slightly more generic about string width. It could potentially be relevant to things like loading a module from the filesystem, where the path contains characters from other languages. Doesn't seem to be a high priority item though.

**Comment by DanRStevens** [comment]
I'm going to go ahead and close this, as we've done all the fixes we're prepared to do at present. We can open a new issue in the future if we want to give a more serious effort towards true unicode support.
