### ISSUE TITLE
Move op2ext.test.cpp contents to StringConversion.test.cpp

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#153]
The `CopyStdStringIntoCharBuffer` method contains tests in the op2ext.test.cpp file. It seems the function moved to a new file, but the tests were not transferred to a corresponding test file. These should now be in StringConversion.test.cpp.

This will leave op2ext.test.cpp empty. It will need to be removed. Logically it should be removed, since that is the static library test suite, and op2ext.cpp has moved to the DLL project.

**Comment by Brett208** [comment]
Sounds like a better organization scheme than what I had for the tests in op2ext.test.cpp.
