### ISSUE TITLE
Remove GlobalDefines.h/.cpp

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#155]
This file contains what are basically logging and reporting type methods. These methods should be moved to Log.h/.cpp instead, and the GlobalDefines.h/.cpp files should be removed.

During this cleanup, we should look at perhaps renaming some of the methods. Perhaps:
`OutputDebug` => `LogDebug`
`PostErrorMessage` => `LogError`

We should also take a look at `DisableModalDialogs` and see if we still need to keep this. Perhaps a change similar to what was done with `Log` could be used here.

**Comment by Brett208** [comment]
The wording PostErrorMessage indicates a modal dialog appears. Are you suggesting, we just log the error and eliminate using the modal dialog with the name change?

I would definitely support changing from OutpostDebug to LogDebug. I'm not really a fan of providing Output to the IDE if we can just log. (There might be a few questionable calls to OutputDebug that should be removed from the code base, I think I removed them in the past).

**Comment by DanRStevens** [comment]
Yes, there is some semantic change in meaning with the proposed rename.

I was thinking we could offer a `LoggerMessageBox`, which could be initially set to handle `LogError` output. The different logging methods could have different loggers set, to account for different levels of logging. It should also be fine if they are set to use a shared logger instance for multiple methods. The code is already using non-owning pointers.

The debug output could also have it's own logger object `LoggerDebug`.

We might also want a `Logger` object that distributes messages to multiple other loggers. That would allow logging to both a message box and to a log file, without having to tie that directly in to message box logging. Not too sure what to call it, maybe `LoggerDistributor`, or `LoggerTee` (though that name kind of implies 1 output to 2 outputs, rather than 1 to many).

The `LoggerMessageBox` and `LoggerDebug` classes would likely be default constructible. That means we could potentially create them on the fly quite easily within the logging code if no logger has been set when they are called. We may want to discuss that though. We probably also don't want to auto create if the user has specially set a `nullptr` for that logging level.

The `LoggerFile` object is not default constructible, due to the required `fileName` parameter. If the logging code is ever reused in another project, I'm not sure there would be a sensible default for that parameter, so I'd want to avoid automatic creation of `LoggerFile` within the logging code.

----

Long term, yes, I'd like to get rid of modal popups for logging. They're quite annoying from a user perspective, and they interfere with testing. For now though, they were easy to code, and they are what we have available. Much better would be a non-modal message log overlay that could be displayed in game, perhaps over the empty area at the main menu screen. We could also perhaps look into system tray style popups, though I'm not sure that would be suitable.

----

I just noticed that although we have a `OutputDebug` wrapper method, which delegates to the `OutputDebugString` Windows API method, most code within op2ext calls `OutputDebugString` directly rather than through the wrapper. We should update that.

We should also review the code to make sure we are logging an acceptable amount of information. I'm fine with it logging the VOL files that get loaded. I noticed there is also logging for module related events. It looks like it was designed for when we only really had a single console module. It seems to have been updated for INI file modules, but with the same design. In particular, it logs the exact same message for every module. It would be better to say once what stage we were at, rather than repeating the same message for every module. If we want output for every module, perhaps to diagnose a crash from an unknown module, then we could output just the module name. That along with the previous output of what stage we were at would provide much more valuable debugging info.

I'm not sure where debugging output goes in Visual Studio. I know OllyDbg can display it. It's pretty out of the way in the log window though, which I almost never look at, so I never really notice it. Sounds like it  may be more intrusive with Visual Studio.

**Comment by DanRStevens** [comment]
C++20 will be adding [`std::source_location`](https://en.cppreference.com/w/cpp/utility/source_location). In the future we could potentially use that to replace the `__FILE__` and `__LINE__` pre-processor macros. In particular, it allows setting a function parameter to a default constructed object, which will capture the location of the caller (not the location of the function declaration). The example they gave looked something like:
```
void log(
    std::string_view message, 
    const std::source_location& location = std::source_location::current()
);
```

To make this work with default parameters, the location needs to come later in the parameter list. This is in contrast to our current use of `__FILE__` and `__LINE__` at the start of the parameter list. We should probably swap that for when defaulting will become a viable solution.

Meanwhile, I've found it's possible to use an extra pre-processor macro layer to handle the `__FILE__` and `__LINE__` defaulting. This may be worth experimenting with.

**Comment by Brett208** [comment]
OK, I understand that you are proposing an interface with logging errors that would allow pushing all error events to a modal dialog. That would be fine with me. Since that is essentially what we are doing already with PostErrorMessage.

**Comment by DanRStevens** [comment]
The core of this issue in the lead post has been resolved. There were a few ideas expressed later in the thread. I'm going to collect those into a new issue and close out this one.
