### ISSUE TITLE
Review code for `std::string_view` opportunities

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#161]
At some point we should review the code for potential [`std::string_view`](https://en.cppreference.com/w/cpp/string/basic_string_view) optimizations.

One caveat is that we need to be careful about using `std::string_view` for return values. As `std::string_view` does not own the buffer it points to, there can be object lifetime issues if it is set to point to a temporary that gets destructed or to an object that goes out of scope.

With that said, it's easy and cheap to construct, so we may be able to avoid forming full `std::string` objects in many cases.

We can potentially write `std::string_view` returning functions that are `constexpr`. This could enable compile time string manipulations.

**Comment by Brett208** [comment]
I found one function that I thought was a good candidate for string_view. Otherwise, nothing else appeared to be a clear win to me (admittedly I'm not good with the new feature). 

I'd like to close this as being fairly generic.

**Comment by DanRStevens** [comment]
I think there are several more possibilities.

While writing the `IniFile` code, I suspected a few places could have used a `std::string_view`.

The `Trim` functions could make use of `std::string_view`. It would be quite natural for the parameters. It would also be reasonable for the return value. That would enable declaring the functions as `constexpr`, which would enable compile time string trimming. There are of course some consequences to safety with a `std::string_view` return value, but I think it is reasonable, especially if documented well. The few uses of `Trim` are all contained within the StringConversion code, which can be checked for return value lifetime issues.

The conversion code between narrow and wide strings may be able to make use of `std::string_view`. Before, when the Windows API was used, the passed data needed to be wrapped in a `std::string`, which limited optimization possibilities. Part of that was due to passing the string to the Windows API, which expected null terminated strings. A `std::string` guarantees it is null terminated, while a `std::string_view` does not. The newer code using the standard C++ library may not need the null termination requirement.

The `ToLower` methods are not likely to be candidates. They modify the actual data, not just the view of the data.

The updated `Split` method may be a candidate. The older code used an `istringstream`, which required a `std::string` backing buffer. That limited optimization possibilities. The newer code uses `find` and `substr`, which are both provided by `std::string_view`. The later of which, `substr`, provides a more efficient implementation, so is a very good candidate for use here.

The `ParseCsv` method is likely to benefit if the underlying `Split` and `Trim` methods can benefit.

The logging code may also be worth looking at.

In general anything that uses a `const std::string&` may be worth looking at. A quick `grep` of the source code shows quite a few uses, though mostly in StringConversion and IniFile.

**Comment by Brett208** [comment]
Considering there are no performance issues inside op2ext, I'm not sure it would be wise to introduce possible safety issues with return values to improve safety. I would rather not have to document such issues or worry about them. There are probably other higher priority areas to work on.

Since the IniFile relies on .c_str, I'm not sure you can use string_view as there is no guarantee a string_view is null terminated.

**Comment by DanRStevens** [comment]
I agree this isn't high priority.

As for safety, that's only relevant to return values. It may also be not all that easy to trigger a non-safe case. And it's always easy to work around those cases by explicitly converting to `std::string`.

We could still potentially make use of `std::string_view` for input values without worrying about safety.

----

Example of unsafe case:
```cpp
FunctionThatCapturesATemporary(std::string_view string);

// Capture a std::string_view with a pointer to a temporary
auto result = FunctionThatCapturesATemporary(std::string("Temporary"));
// At this point the std::string temporary will be destructed

// Use dangling pointer
std::cout << result;
```

To make that safe, change one line:
```cpp
auto result = std::string(FunctionThatCapturesATemporary(std::string("Temporary")));
```

To make the compiler catch that something is wrong, don't capture with `auto`:
```cpp
std::string result = FunctionThatCapturesATemporary(std::string("Temporary")); // Error, can't convert from std::string_view to std::string (this must be explicit)
```

**Comment by Brett208** [comment]
I think the functions targeted for this issue have all been deleted from the code base.

**Comment by DanRStevens** [comment]
Yeah, there doesn't seem much left to go over for this. That coupled with lag in standard library support for `std::string_view` means opportunities seem a bit minimal at present.

Let's just close this then.
