### ISSUE TITLE
Report errors in a single pop-up message box

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#167]
There are a few places in the code with pop-up message box errors at multiple levels. This can cause multiple pop-up message boxes to appear for a single error. We should reduce the reporting to a single pop-up message box for what is conceptually a single error.

One way to do this, is to replace the lower level error reporting with exceptions, and then collate the error messages at the higher level to report them. This can be done by effectively wrapping error messages, so when a higher level error is thrown, the text includes the `exception.what()` text from the lower level error.

More long term, it would be nice to move away from modal pop-up boxes that require the user to click close. Such model boxes can be annoying to users, and are also an impediment to automated testing.

**Comment by Brett208** [comment]
I agree with consolidating modal dialogs so multiple do not appear for a single issue. 

I'm not sure I would support removing the modal dialogs unless there is a different way to directly and immediately let the user know they are experiencing a serious problem. For example with the module NetHelper, everything is behind the scenes. The user would not know there was a problem with the module unless they search through the log files.

**Comment by DanRStevens** [comment]
Immediate visual feedback is fine. Just as long as it's non-modal. There should be no required user interaction to dismiss the error, or to continue. Examples would be asynchronous system tray popup notifications, which auto dismiss themselves after some timeout, or an overlay log display at the main game menu.
