### ISSUE TITLE
Update module index order specification

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#185]
For the op2ext.dll exported method `GetLoadedModuleName`, we specified module index order as:
```cpp
// Ini modules are indexed first and console module is last.
```

I think we should remove that specification. The order can be considered an internal detail. There is little reason for calling code to know or care what order the various types of modules are returned in. They only need to know they are returned in some order, and perhaps that order will remain consistent once loaded.

If we wish to provide any external specification, perhaps we should instead state they are indexed in module load order. As we update to allow for built in modules, console modules, and ini modules, it can remain naturally correct.

----

As for the actual order, there was some discussion to use the new order:
1. Built-in
2. Console
3. INI

----

I might also propose we consider swapping the order to:
1. Built-in
2. INI
3. Console

The INI modules are in some ways closer to Built-in modules than Console modules. They're a bit like larger and perhaps less stable built in modules. As they require manual file editing to swap out, they are more permanent than console modules.

**Comment by Brett208** [comment]
I think we want resources from console modules loaded before resources from an ini module. If a console module is the easiest to swap out, it should take precedence in say which tech file is selected over an ini module (assuming ini modules can eventually load resources).

I would propose for resource loading and patching priority:
1. Console
2. Ini
3. Built-In (doesn't really apply I suppose)

The Load, Run, and Unload functions on modules should be called in reverse order so patches applied by more stable modules are overridden by the more transient modules. So:
1. Built-In
2. Ini
3. Console

This way a console module change would override a patch made by a built-in module or an ini module. And a patch made by an ini module would override a built-in module.

**Comment by DanRStevens** [comment]
I agree. Let's do that.

Slight clarification: By loaded before, I assume that means higher priority during resource lookup, and not simply the VOL files or module directories were added to the search path first. Resource priority order is the reverse of the module load order. This might be implemented by traversing lists backwards, or it might be implemented by reversing arrays.

**Comment by DanRStevens** [comment]
Moving the following comment over from issue #186. This is a better issue to house the comment.

----

In `ModuleLoader::LoadModules()` the current order (set in 77cecbfb in PR#190) is:
```cpp
RegisterConsoleModules();
RegisterBuiltInModules();
RegisterIniModules();
```

After the `GetConsoleModDir_s` update proposed above, the module load order in `ModuleLoader::LoadModules()` could be set (as desired in issue #185) as:
```cpp
RegisterBuiltInModules();
RegisterIniModules();
RegisterConsoleModules();
```

----

PR #276 should unblock this issue.
