### ISSUE TITLE
FileSystemHelper should isolate from `<filesystem>`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#192]
Currently FileSystemHelper.h has a direct import of `<filesystem>`. This should be moved from the .h file to the .cpp file.

Currently none of the methods provided by FileSystemHelper actually need `<filesystem>` for their signatures. As such, this should be an easy move. However, a number of code files import FileSystemHelper.h as a way of indirectly importing `<filesystem>`, and then directly use `<filesystem>` methods.

To ease the transition, we could create a FsInclude.h file, which contains the various ways of importing `<filesystem>`. This could be used in place of FileSystemHelper.h for code that really needs direct access to `<filesystem>`.

We could reduce the need for includes of `<filesystem>` by using new methods, such as `IsDirectory` and `Exists`, introduced in PR #191. This also reduces the need for proliferating compiler specific workarounds throughout the code.

As this change may affect many files, we should try to do it when there are no large outstanding PRs.

**Comment by Brett208** [comment]
Since we are explicitly using C++17 features such as string_view, I'm not sure this is still an issue. I think the compiler has to be C++17 compliant now where as in the past the only C++17 feature we were using was the filesystem.

-Brett

**Comment by DanRStevens** [comment]
Yes, that's a valid point. As it is part of the standard I was also thinking we should be a bit more free in direct use of the `<filesystem>` header. One of the concerns here is of course that full and proper implementation of the standard in currently available compilers is still sometimes a bit lacking. In particular, `fs::exists`, `fs::is_directory`, and `fs::remove` (unit test project only) have all been problems in this project. I don't think we need to go so far as to wrap all filesystem access, such as in OP2Utility, though I admit I have sometimes been a bit tempted.

There are 2 main points in this issue:
1) Minimize the spread of compiler specific hacks and fixes. (`Exists`, `IsDirectory`).
2) FileSystemHelper.h includes `<filesystem>` but doesn't actually use it.

The second point means use of `FileSystemHelper.h` is a bit unclear as to intent. Is it being included for the direct exports it provides? Or is it being used as an easy way to add an indirect include to `<filesystem>`. Splitting these two uses provides more clarity.
