### ISSUE TITLE
Review INI section and key names before next release

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#214]
Some updates have been made to the INI section and key names. We should review these before the next release. Once they are out, they become part of the public interface, and we should strive to keep that as stable as possible. At the very least, minimizing external changes minimizes what users have to re-learn about using the software. It may also ease porting settings between versions.

Module loading has added sections for built-in modules, and INI modules that need to be reviewed.

----

From a source code maintenance perspective, we should avoid duplicating string literals for these names.

**Comment by DanRStevens** [comment]
Side thought before I go. The INI modules are named after their particular implementation. From the user perspective, it may be better to use a name based on purpose.

The same can be said for console modules.

**Comment by Brett208** [comment]
@DanRStevens, did you want to take another look at the names before release? I think this is the last issue to decide on.

**Comment by DanRStevens** [comment]
I suspect the concerns were addressed when the changes were made. I suppose we should at least summarize the changes before closing the issue. I'm not super eager to make any changes, but that might just be my particular mood at this exact moment since I'm kind of tired right now.

**Comment by Brett208** [comment]
From the ReadMe:

```
Remove the LoadAddons line from the Game section (it is now replaced by the ExternalModules section)
[Game]
LoadAddons = "NetFix, NetHelper"

Add the following sections to the ini file:

[BuiltInModules]
EarthworkerProximityTasking = yes
IPDropDown = yes

[ExternalModules]
NetFix = yes
NetHelper = yes
```

I think the intention with this issue is to make sure we are happy with the section and property names above.

There was some discussion about standardizing the terms in a module name (property name in the ini file).

I'm okay with moving forward, but am also not against considering changes if something comes to mind.

**Comment by DanRStevens** [comment]
Thank you for the summary. I think it's probably fine. I think we can close this.
