### ISSUE TITLE
How to pull module count and names into an ini module

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#216]
If Ini modules pull other loaded module names or count during their run function, they may not catch all loaded modules.

Perhaps we should add a run function similar to console modules. Or if there is a way to accomplish this without a new function, it should be documented as a comment on the associated op2ext functions.

**Comment by DanRStevens** [comment]
More generally, what event hooks should be offered to modules. There are probably other useful events we could define. Perhaps an event can fire every time the player returns to the main menu. Or perhaps we can have events when entering or exiting the multiplayer section of the game.

In terms of the run function, is there a particular use case you had in mind? I assume this is something you noticed from test code.

----

What if both IniModule and ConsoleModule were handled by the base DllModule class? The main difference between the classes are the names and signatures of the expected DLL exports. As all methods are currently optional, we could potentially just define a global order of calling. Maybe call methods in the following order, if they exist:
- `InitMod`
- `mod_init`
- `mod_run`
- `mod_destroy`
- `DestroyMod`

That would allow any module to declare a `mod_run` function, and expect it to be called at the right time.

**Comment by Brett208** [comment]
I picture an ini module that pulls a list of loaded modules and displays it to the user. Maybe on the main menu. All modules must be loaded before it can fetch their names.

Defining a run function for ini modules would do the trick.

**Comment by Brett208** [comment]
I like the idea of folding the functions into DllModule.

Some modules declare both InitMod and mod_run so they can be loaded as either a console module or an ini module. We should make sure we do not execute both versions of the function. I think maybe we could:

1. Check if InitMod exists.
2. If InitMod exists, use reference to this function for Load.
3. If IniMod does not exist, check for mod_init and reference this function if it exists.

Then repeat that pattern for mod_run and DestroyMod.

I would also like to deprecate mod_init, mod_destroy, and mod_run. 

We could just make the standard calls for both console modules and ini modules InitMod, RunMod, DestroyMod.

This is starting to get away from the actual issue though.

**Comment by DanRStevens** [comment]
I suppose some modules might care if  you called both corresponding methods. I guess I'm making assumptions about how robust existing modules are.

I'm fine if INI style methods are prioritized over the console methods. It could go either way, except for `InitMod`, which needs access to the parameter when loaded as an INI mod.

We may want to be cautious about mixing calls. Should we only call `mod_destroy` if we called `mod_init`? We might need to if the module exports ` mod_destroy` but no `mod_init` to be consistent with previous code. Though if a module exports `InitMod`, `mod_init`, and `mod_destroy`, it becomes less clear what to do if we call `InitMod` instead of `mod_init`.

This does seem to be leading away from the original problem. Though perhaps the original problem had a lot of underlying subtlety.

**Comment by Brett208** [comment]
Agreed, the original problem exposed more than expected to handle. 

I'll program a branch that favors INI module function names over ConsoleModule names to see how it looks.

I think at this time more complex logic to ensure only one set of names is called is not worth the effort. If you think it is important, I can take a stab at making it work. It would be something along the lines of choosing a function schema based on the first detected function (So if no InitMod/mod_init function found, try the check on Run, and then on Destroy).

**Comment by Brett208** [comment]
Agreed, the original problem exposed more than expected to handle. 

I'll program a branch that favors INI module function names over ConsoleModule names to see how it looks.

I think at this time more complex logic to ensure only one set of names is called is not worth the effort. If you think it is important, I can take a stab at making it work. It would be something along the lines of choosing a function schema based on the first detected function (So if no InitMod/mod_init function found, try the check on Run, and then on Destroy).

**Comment by DanRStevens** [comment]
Sounds good.

... thought I should point out, you are going down the path of more complex logic to ensure only one set of names is called. :wink:

**Comment by Brett208** [comment]
I'm closing this as resolved since you can now call the Run function on an Ini module to get the full count.
