### ISSUE TITLE
Better distinguish between Log and Logger classes

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#231]
I find it difficult to distinguish between a Log and Logger in the code base.

Maybe we could rename Logger to ILog or LogInterface? ILog is pretty standard in C# conventions, but LogInterface might be better here.

This would look like:
```C+++
void SetLogInterface(LogInterface* newLogInterface);
void SetErrorLogInterface(LogInterface* newLogInterface);
```

I would prefer SetErrorLogInterface to SetLogErrorInterface, however, I could live with either option.

Open to other suggestions as well. I've tried to adapt to using the current syntax (Log and Logger), but it doesn't seem to be sticking for me.

**Comment by DanRStevens** [comment]
I suppose that is a bit strange.

I'm not terribly fond of the "I" prefix for interface classes. We've been avoiding prefixes on names in most of the projects, so it would seem a bit odd to start now.

Spelling out "Interface" within the name seems less objectionable, though I'm not terribly fond of that either.

We can't share the name `Log` between a global function and a global class. We could perhaps wrap the global methods into a `Log` class namespace, making them static methods. That would however require changing calls to look something like `Log::Log()`, or `Log::Error()`. I'm a little ambivalent towards that idea too. I suppose it would provide logical grouping of methods though. And we could then combine the Log.h file with Logger.h.

**Comment by Brett208** [comment]
I would be fine with the namespace idea. It would look like the Stream namespace in OP2Utility. Stream::Reader and so on. We could go with:

```C++
Log::Debug();
Log::Standard(); // instead of Log::Log
Log::Error();
```

**Comment by DanRStevens** [comment]
I wouldn't mind avoiding `Log::Log`, but I find `Standard` doesn't sound very descriptive, especially when taken out of context of the other two methods. Maybe `Log::Message`?

**Comment by DanRStevens** [comment]
I was just thinking, if we rename `Log` to something like `LogMessage`, would could then rename the `Logger` class to just `Log` and there would be no name conflict. That means we don't have to move the global methods into static methods within the class namespace.

The `Logger` details are more of an internal dispatch mechanism. Most code that makes calls to logging doesn't need to know these details. As such, it may make sense to keep the Log.h and Logger.h header files separate. We may of course want to rename them if the class gets renamed to `Log`.

**Comment by Brett208** [comment]
I am good with trying out LogMessage. That seems pretty clear on intent.

I think Log is too generic a name for a class. Does it mean the action of Logging something or the log file/destination itself?

I just saw the subfolder suggestion and independently opened an issue for it.

-Brett

**Comment by DanRStevens** [comment]
Based on context, I would assume a class/object would use a noun phrase, and hence denote the destination. For a function call, I would assume a verb phrase, and hence it denotes the action.

I suppose it is easy to forget that `Log` is a bit ambiguous in that it can be both a noun or a verb.

I'm happy using "Log" in both contexts.

I'm just kind of realizing now, if we do rename `Logger` to `Log`, we'll still have a `Log::Log` method (an actual member, not a static one). Oddly, it would use "Log" in both contexts. I think I'm fine with that though.

Mostly though, I don't have a better name to suggest.

**Comment by DanRStevens** [comment]
Where do we stand on this issue now? Some method renaming has been done. Do we want to also rename the classes? I'm open to renaming things.

After reviewing the code, I would like to maintain a distinction between Log.h and Logger.h. Typical code that needs logging support doesn't need to know the details of the `Logger` class. That's all internal implementation/dispatch detail within the logging code. The only external point where that is relevant is where the loggers are created and then set, or when deriving new loggers. Most code isn't concerned with those aspects and simply just calls one of the Log methods.

I would be fine with renaming the `Logger` class to just `Log`. We'd need to so some name shuffling of the source files though. Not sure what we would call Log.h in that case.

**Comment by DanRStevens** [comment]
I was just thinking, my solution here was to reduce the distinction, rather than increase the distinction.

Although there is a distinction, there are few contexts where you need both.

Tagging #250 as related.

**Comment by DanRStevens** [comment]
Issue #250 dealt with creation of a "Log/" subfolder. There was also discussion about class renaming. This might be the better issue for that discussion.

Do we want to rename the `Logger` classes? And if so, to what? I had suggested simply just `Log`. It seems you might want a more distinct name though. Maybe `LogDestination` for the generic interface class, which denotes logging to any arbitrary destination? We could also go with `LogSink` to use a shorter more technical name. Though there doesn't seem to be any corresponding `LogSource`, so I don't know how well it fits.

**Comment by Brett208** [comment]
I think LogDestination would work. It is more descriptive and clearer than Logger to me. If a class subscribes to the LogDestination interface, it is able to write to an appropriate log that it defines.

**Comment by DanRStevens** [comment]
Ok then, let's rename the `Logger` base class to `LogDestination`.

What about derived classes? Should we change the `Logger` portion of their names to `LogDestination`? Or should we perhaps just drop the `Logger` portion of the name? It should be clear in the context of the "Log/" folder what the classes apply to, though we might want to add some kind of namespacing. Though a namespace would be little different than a name prefix.

I suppose we could go with a namespace or prefix of just `Log`, where the rest of the name takes the place of `Destination`.

**Comment by Brett208** [comment]
I think just using Log as prefix on file and class names will work okay (not that I am opposed to the namespace idea if preferred).
