### ISSUE TITLE
OP2Memory - data types

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#273]
There are a few uses of `std::size_t` that are perhaps better as `std::uint32_t`. In paritcular, the parameters marked as `dword` should probably be changed.

Of course, this library is designed for in-process modification of 32-bit code on x86 for Windows, so there are already plenty of assumptions built in. It would be very unexpected if `std::size_t` was ever different than `std::uint32_t`. Still, it may be more correct to use a fixed width data type.

----

There is a built in assumption that `GetModuleHandle` will return a `void*`. In actuality it returns a `HANDLE`, which is typically typedef-ed to be a `void*`. Following is an `if` call that assumes failure is indicated by `nullptr` rather than the documented `NULL` value. It just so happens that `NULL` is typically defined in a way that is compatible with `nullptr`.

**Comment by Brett208** [comment]
I like the idea of switching to uint32_t where appropriate for readability. When I see size_t, I expect the exact size to shift based on the architecture. When I see uint32_t, I know the size was fixed for a reason by the programmer.

It is nice if most of the code is able to be lifted into an x64 application if ever desired, although agreed it will have little impact on op2ext itself.
