### ISSUE TITLE
Show error when module fails to load

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#37]
Currently the IniModuleLoader will display an error message if a module fails to load. The console module loader does not, and instead fails silently. This should be improved.

In particular, this code section silently ignores a module that fails to load:
https://github.com/OutpostUniverse/op2ext/blob/831f2100fd10be2e2c8b7a7d3b07e1bf0dfd89f1/ConsoleModuleLoader.cpp#L73-L81

**Comment by Brett208** [comment]
I'll take this project on shortly.
