### ISSUE TITLE
Run mingw unit tests on CI

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#68]
Pulled from issue #47. All research done by @DanRStevens. Previous issue had significant discussions about unit test implementation that wasn't relevant to mingw work.

---

As this is a Windows only project, we'd need to use Mingw to compile from Linux. This requires a bit of special setup for Google Test. In particular, when building Google Test, we must set the command line option to cmake: `-DCMAKE_SYSTEM_NAME="Windows"`. Additionally there are some pthread issues when compiling gtest with Mingw. These are avoided by running cmake with the command line option `-Dgtest_disable_pthreads=ON`. These options can be added to the makefile.

There are additional complications when compiling the test code (as opposed to Google Test itself). To reference the Google Test library, we use `#include <gtest/gtest.h>`. The system installed headers are found in `/usr/include/gtest/`, hence we need an include directory of `-I/usr/include`. Unfortunately, this brings in standard Linux system header files, which conflict with the Mingw specific header files for Windows cross compilation. To get around this, we can change the include directory to be more specific with `-I/usr/include/gtest/`, and then update the source code inclusion to `#include <gtest.h>`. Unfortunately, Google Test itself includes it's other header files by using `gtest/` as part of the path, so those headers won't be found. The solution I found was to copy the `/usr/include/gtest/` folder to another location, perhaps `.build/include/gtest/`, and then add `-I.build/include/` as an additional include folder. That way it brings in gtest, but not the rest of the Linux system libraries.

This would be easier if Google Test didn't depend on the parent folder of the `gtest/` folder being in the include path.

**Comment by DanRStevens** [comment]
PR #48 included the necessary `makefile` changes to implement the details above.

What remains to be done is to get the unit tests running on the CI servers. Right now it can't due to an inadequate test environment. There is an open branch `addCircleCiConfig` (with no PR) which adds changes to the `Dockerfile` to setup a test environment. It's not quite finished and tested yet. Once the changes are complete, a PR will be opened for the branch.
