### ISSUE TITLE
filesystem throws an exception when non-experimental version used

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/op2ext#78]
When compiling with the non-experimental version of filesystem, I am getting the exception below in both Debug and Release builds. 

<img width="700" alt="Directory_Iteratory_Exception" src="https://user-images.githubusercontent.com/15183337/56703936-3682f800-66d9-11e9-92f1-3da14ddcd5b0.png">

If I force it to build with the experimental filesystem include and namespace using, then it works properly.

Unless an easy fix is available, I would like to regress this change so we can get a release out. I didn't catch this until Monday and don't know what to do to fix.

-Brett

**Comment by DanRStevens** [comment]
We should add unit tests to demonstrate the problem. Would be nice to get down to a root cause.

I believe there are some differences in the specification of `<filesystem>` between the officially adopted version and the experimental version. Perhaps we should become more familiar with those differences.

I'd be hesitant to backdate without first understanding what's going wrong.

**Comment by Brett208** [comment]
Sorry, this needs to be rolled back until understood. Troubleshooting can happen in a separate branch in addition to adding unit tests. 

Otherwise, anyone compiling the master branch with MSVC will experience crashes when loading Outpost 2. 

This is my fault for not actually loading Outpost 2 up when implementing the non experimental filesystem.

**Comment by DanRStevens** [comment]
I believe it may be related to this method:
https://en.cppreference.com/w/cpp/filesystem/path/remove_filename
https://en.cppreference.com/w/cpp/experimental/fs/path/remove_filename

In particular, this method had a change of behavior when the filename is absent.

----

Curiously, while testing on Linux with Mingw, I found the `GetGameDirectory()` method was returning the executable's folder/filename, not just the folder. That could cause other methods to fail that were expecting a foldername, but instead got a filename.

**Comment by Brett208** [comment]
Thanks for jumping on adding unit tests so quickly to help figure this out. I'll read through the links you posted and try playing with the unit tests some.

**Comment by Brett208** [comment]
Okay, I think this error is caused when applying the directory iterator to the relative path 'addon'. op2ext will search for vol files there. This throws a filesystem_error, which can be caught. This behaviour must have changed between expiremental and here.

Perhaps we should solve by:
1. checking if the directory exists before running the iterator
2. adding a try/catch to the directory_iterator. Maybe dump the contents to the log file at this point and continue.

"directory_iterator::directory_iterator: The system cannot find the path specified.\r\n: \"C:\\ . . . \\Outpost2\\Addon\""

<img width="906" alt="filesystemError" src="https://user-images.githubusercontent.com/15183337/56839676-a1efd580-6851-11e9-877d-0f818ecca4ff.png">
