### ISSUE TITLE
Rename `GetOP2PrivateProfileString`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#84]
I was looking at `GetOP2PrivateProfileString` and thinking it should be renamed. Perhaps:
`GetOutpost2IniSetting`

That would be more consistent with the existing `GetOutpost2IniPath`.

It also avoids just re-using the Windows method name `GetPrivateProfileString`, which is mostly just an internal implementation detail, and not a very descriptive name.

----

We should wait until open pull requests touching the code settle before doing this.

**Comment by Brett208** [comment]
I'm content either way.
