### ISSUE TITLE
Refactor `GetPrivateProfileStdString`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#85]
We should refactor `GetPrivateProfileStdString` to remove the internal use of `new` and `delete`. We should instead rely on [`std::string::resize`](https://en.cppreference.com/w/cpp/string/basic_string/resize) to allocate the buffer space.

Additionally, we may consider moving this method out of `FileSystemHelper.h`, which doesn't seem to be a great home for it. I would be fine if the method got its own file.

----

We probably want to write a few unit tests before doing the memory allocation refactor.

**Comment by Brett208** [comment]
No problem using a std::string for implementation. I think I wrote this before I understood std::string well enough to rely on resize among other things. 

Agreed it does not really belong in FileSystemHelper. I'm not sure how I feel about fragmenting into a decent number of .h/.cpp files that contain single tasks. No worse a plan than where I stuffed it though so happy if it is moved onto its own.
