### ISSUE TITLE
Reduce code duplication in `Op2MemCopy` and `Op2MemSet`

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/op2ext#99]
We have two nearly identical functions, `Op2MemCopy` and `Op2MemSet`. They differ only in one line, where it calls either `memcpy` or `memset`.

https://github.com/OutpostUniverse/op2ext/blob/189f54da0755b5ba5c6c86f35325811ad129e13e/srcStatic/OP2Memory.cpp#L21-L40

We can reduce duplication by having a generic memory unrpotect / reprotect method, which instead calls a lambda at the `memcpy` / `memset` line. The two methods can then be written in terms of one generic function and two small lambdas.

**Comment by Brett208** [comment]
I have considered this as well.
